; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2w]
platform = raspberrypi
board = rpipico2w
framework = arduino

monitor_speed = 115200
monitor_encoding = UTF-8

lib_deps =
    lovyan03/LovyanGFX@^1.2.26
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4